### ISSUE TITLE
sap file

### ISSUE THREAD

**Issue by fr4ncidir** [desmovalvo/sap-documentation#1]
I would like to suggest an addition to the sap respec. "The .sap file _should not_ be modified at runtime. If you feel the need to modify at runtime a sap file, you may consider instead to add _new_ sap files for your purposes, or _change_ the current one or _change_ your sparql code."

**Comment by lroffia** [comment]
I completely agree with you! 


Inviato dal mio dispositivo Samsung

-------- Messaggio originale --------
Da: Francesco Antoniazzi <notifications@github.com> 
Data: 04/05/2017  12:16  (GMT+01:00) 
A: vaimee/sepa-documentation <sepa-documentation@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Oggetto: [vaimee/sepa-documentation] sap file (#1) 

I would like to suggest an addition to the sap respec. "The .sap file should not be modified at runtime. If you feel the need to modify at runtime a sap file, you may consider instead to add new sap files for your purposes, or change the current one or change your sparql code."

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vaimee/sepa-documentation","title":"vaimee/sepa-documentation","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/vaimee/sepa-documentation"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"sap file (#1)"}],"action":{"name":"View Issue","url":"https://github.com/vaimee/sepa-documentation/issues/1"}}}
